---
- name: Chatty
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 240 # 30 days
        delay: 1
  rules:
    - name: Say Hello long running
      condition: >
        event.i > 5
      action:
        debug:
          msg: "{{ '$' * 1000 }}"
