---
- name: Long Running Range
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 2592000 # 30 days
        delay: 1
  rules:
    - name: Say Hello long running
      action:
        debug:
          msg: 'Hello World!, event.i = {{ event.i }}'
