---
- name: Long Running Range
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 120 # 30 days
        delay: 1
  rules:
    - name: Say Hello long running
      condition: >
        event.i > 5
      action:
        debug:
          msg: "{{ '$' * 50000 }}"
